devtics_task:
    resource: "@DevTicsTaskBundle/Resources/config/routing.yml"
    prefix:   /task/

devtics_hello:
    resource: "@DevTicsHelloBundle/Resources/config/routing.yml"
    prefix:   /

devtics_admin: 
    pattern: /admin
    defaults: { _controller: DevTicsHelloBundle:Security:admin}
    
    
login:
    pattern: /login
    defaults: { _controller: DevTicsHelloBundle:Security:login}


login_check:
    pattern: /login_check
