security:
    encoders:
        DevTics\HelloBundle\Entity\Usuario:
            algorithm: sha512
#            encode-as-base64: true
#            iterations: 10

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        
    providers:
        user_db:
            entity: { class: DevTics\HelloBundle\Entity\Usuario, property: usuario}
    
    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 18000
                path: /.*
                domain: ~
            security: true
            anonymous: true
        
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /user, roles: ROLE_USER}
        - { path: /admin, roles: ROLE_ADMIN}
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }