devtics_hello_homepage:
    path:     /hello/{name}
    defaults: { _controller: DevTicsHelloBundle:Default:index }
    
devtics_hello_homepage2:
    path:     /tt/
    defaults: { _controller: DevTicsHelloBundle:Default:tt }

devtics_get_products:
    path: /gp/
    defaults: { _controller: DevTicsHelloBundle:Default:getProducts}
#devtics_hello_recentArticles:
#    path: /recentArticles/{max}
#    defaults: { _controller: DevTicsHelloBundle:Default:recentArticles}
    